### PR TITLE
Fixes for job bosh-dns-windows to support logging tags

### PR DESCRIPTION
**Pull request by a-hassanin**
Fixes https://github.com/cloudfoundry/bosh-dns-release/pull/96

### CODE REVIEW

**Review by beyhan — APPROVED** [review]

**Comment by beyhan** [comment]
@jpalermo we missed to include this pr in the [v1.37.0](https://github.com/cloudfoundry/bosh-dns-release/releases/tag/v1.37.0) release. We discussed this with @a-hassanin [here](https://github.com/cloudfoundry/bosh-dns-release/commit/cb9a1f4fcbfc6c217b8dad08f0a1abb962ba5835) but I forgot to notify you in Slack.

**Comment by jpalermo** [comment]
Seems like there is a bigger problem. The tags properties aren't used in the windows config.json template.

**Comment by a-hassanin** [comment]
> Seems like there is a bigger problem. The tags properties aren't used in the windows config.json template.

@jpalermo Ahhh yes you are right, bosh-dns-windows was missing it.

**Review by jpalermo — APPROVED** [review]
👍

**Pull request merged**
