### PR TITLE
add option to resolve agent_id in dns.

### PR DESCRIPTION
**Pull request by andyliuliming**

### CODE REVIEW

**Comment by andyliuliming** [comment]
@cppforlife @luan @jaresty @jraqula @monkeyherder could you please help review : )

**Comment by dpb587-pivotal** [comment]
@andyliuliming thank you for the pull request. To reduce confusion, please avoid tagging individual contributors who do not have context on the changes being proposed.

For reference, when pull requests are received, they are briefly reviewed by @cppforlife and then prioritized into the team's backlog for code review and merge. Sometimes it does take us a little time to get to these given the team's range of responsibilities, and we appreciate your patience.

If there are specific concerns or pressures this relates to, please do feel free to mention them when discussing the original issue or when making the pull request. That can help provide a bit more context and help us better understand your needs and priorities.

Thanks again - we'll try to get to this shortly!

**Comment by andyliuliming** [comment]
prefer https://github.com/cloudfoundry/bosh-agent/pull/174  so close this PR.

**Comment by svrc** [comment]
I'd like to re-open this one as supporting Azure PKS with bring-your-own DNS would be solved by this patch more easily than expecting the customer to have dynamic DNS or using Azure DNS all the time

**Comment by mfine30** [comment]
Going to re-open this so we get a tracker story for prioritization

**Comment by cjnosal** [comment]
Closing - This feature was reworked and implemented in https://github.com/cloudfoundry/bosh-dns-release/commit/384bd1ef04d2410c15024ed1addbd04f5ceca3e3
https://github.com/cloudfoundry/bosh-dns-release/commit/1d974155a4586a138820d2a49482263b3b2b0490

**Pull request closed without merging**
