### PR TITLE
add support for the alias file auto refreshing.

### PR DESCRIPTION
**Pull request by andyliuliming**
added the support for the alias files auto refreshing.
now if some files updated, it will reflect in 1 minutes(checking interval).

and the unit test will pass after this PR merged. 
https://github.com/cloudfoundry/bosh-utils/pull/48

### CODE REVIEW

**Comment by andyliuliming** [comment]
@mfine30 could you please help create one story on this if you think it has some value? thanks.

**Comment by mfine30** [comment]
@andyliuliming thanks for the PR. I'll review it with the team today. We have this story to track it though: https://www.pivotaltracker.com/story/show/159710058

**Comment by andyliuliming** [comment]
any updates? 🍺 : )

**Comment by mfine30** [comment]
Hey @andyliuliming, just reviewing this now - sorry for the delay. 

The alias functionality is intended to be a simpilstic form of aliasing, and updating records on the VM on the fly outside of BOSH doesn't adhere well to our goals for the aliases feature. BOSH DNS does support custom handlers, which is probably better suited to enable the use case you're trying to solve for here.

In particular, the custom [handler](https://bosh.io/jobs/bosh-dns?source=github.com/cloudfoundry/bosh-dns-release&version=1.10.0#p%3dhandlers_files_glob) functionality is intended to support services that can dynamically change their answers, whereas the aliases feature is intended to be more static across a deployment.

**Comment by ships** [comment]
I am in progress trying to get a basic deployment of [powerDNS](github.com/cloudfoundry-community/pdns-release) collocated with a BOSH DNS in order to accomplish an CRUD api for entries discoverable by BOSH vms, using the handlers system as mentioned above. I'll write back when I make more headway, but it seems like much more suitable to the BOSH opinionated paradigm than dynamically loading aliases, which BOSH cannot guarantee will live very long.

**Comment by andyliuliming** [comment]
ok, got it.
then I think whether we can implement the "default alias loader" as a handler too : )
will close the PR.

**Pull request closed without merging**
