### PR TITLE
Fix issue #41 - DNS Server Cache Snooping Remote Information Disclosure

### PR DESCRIPTION
**Pull request by gu-bin**
https://github.com/cloudfoundry/bosh-dns-release/issues/41

### CODE REVIEW

**Comment by gu-bin** [comment]
@dpb587-pivotal

**Comment by dpb587-pivotal** [comment]
* please run `go fmt` on your changes to ensure consistent formatting with `go` standards.
 * can you provide background on why you chose the `RcodeRefused` response code?
 * can you provide context on whether clients of `.arpa` addresses behave any differently in their lookups to help determine if this would be considered a breaking change?
 * I don't think we should be changing the cache handler behavior because it is not directly responsible for resolving queries.

**Comment by dpb587-pivotal** [comment]
oh, sorry; cc @luan for further feedback of this

**Comment by gu-bin** [comment]
@dpb587-pivotal 
> please run go fmt on your changes to ensure consistent formatting with go standards.

OK, I've run `go fmt` and the commit is in the PR.

> can you provide background on why you chose the RcodeRefused response code?

`REFUSED` obviously tells the clients that the server refused to answer for the query. If the server replied the query that has no `recursion desired bit` set, it will have `DNS Server Cache Snooping Remote Information Disclosure` problem. I think `REFUSED` is the best return code in such a situation. Or we can just provide no answer as `PowerDNS` does? If you think another return code is better, I can change the PR.

> can you provide context on whether clients of .arpa addresses behave any differently in their lookups to help determine if this would be considered a breaking change?

I don't think there is any difference in .arpa address queries. Clients can still have `recursion desired bit` set or not set. 

> I don't think we should be changing the cache handler behavior because it is not directly responsible for resolving queries.

If it's confirmed that the cache handler is behind other handlers and doesn't directly resolve the queries, I can remove the change from the PR. 

I'm not a DNS expert. All the comments above are within my knowledge. Need a DNS expert from the community to look into it. Thanks.

cc @mattcui

**Comment by luan** [comment]
Hi @gu-bin,

We looked at `dnsmasq` and found out that they actually changed their caching behavior on 2.80. They now always forward (skipping the cache) when RecursionDesired is not set.

From their [CHANGELOG](http://thekelleys.org.uk/dnsmasq/CHANGELOG):
> Change anti cache-snooping behaviour with queries with the recursion-desired bit unset. Instead to 
 returning SERVFAIL, we now always forward, and never answer from the cache. This allows "dig +trace" command to work. 

We think it makes sense to do the same thing they do.

We also looked over your changes and you've added code to all the different handlers when this change only belongs to the `CachingDNSHandler`. Can you implement the same behavior that `dnsmasq` has but only in the `CachingDNSHandler`? Just be be clear, the behavior is to skip the cache and go straight to `ForwardHandler` when `RecursionDesired` is false.

Something like:

```go
if !r.RecursionDesired {
    return c.next.ServeDNS(w, r)
}
```

At the top of `CachingDNSHandler#ServeDNS`.

Thanks,
@luan, @jaresty, @pivotal-mp, CF BOSH DNS Team

**Comment by gu-bin** [comment]
@luan, @jaresty, @pivotal-mp, CF BOSH DNS Team
I updated the PR as you suggested. Please review again. BTW, I found `c.next` is not initialized in `NewCachingDNSHandler`. I fixed it also in the PR. Please let me know if it's not correct. Thanks.

**Pull request merged**
